title: Angela Bravo
email: bravomar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Angela Bravo : production designer, art director, interior designer living
  between Los Angeles, CA and Mexico City.
baseurl: ""
url: "http://angelabravo.net"

# Build settings
theme: minima
plugins:
  - jekyll-postcss
postcss:
  cache: false

collections:
  projects:
    output: true
    permalink: /:collection/:title
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
